"""Render ``docs/DATA_AUDIT.md`` from ``reports/data_audit.json``.

Generated rather than hand-written so the document cannot disagree with the
code. Every number below traces to a value the audit actually computed — which
matters more than it sounds, because a hand-transcribed audit is stale the
first time anyone changes a rule.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from mlservice.config import PROJECT_ROOT
from mlservice.logging_ import get_logger

log = get_logger(__name__)

DISCLAIMER = (
    "> **NOT A CREDIT DECISIONING SYSTEM.** This document reports an "
    "engineering data audit on a public research dataset. Nothing in it is "
    "validated for lending, and it must never be used to decide anyone's "
    "access to credit.\n"
)


def _pct(x: float) -> str:
    return f"{x * 100:.2f}%"


def _normalise_markdown(text: str) -> str:
    """Insert the blank lines markdown needs, without breaking tables.

    Blocks are appended piecemeal, so headings and tables can end up flush
    against the preceding line. A heading or table not preceded by a blank line
    fails to render on several engines, GitHub's included.

    Naively joining blocks with a blank line is *wrong* — table rows are
    appended one at a time, and separating them would destroy the table. So the
    rule is applied per line, with consecutive ``|`` rows kept together.
    """
    lines = text.split("\n")
    out: list[str] = []
    for line in lines:
        stripped = line.strip()
        needs_gap = stripped.startswith("#") or (
            stripped.startswith("|") and not (out and out[-1].strip().startswith("|"))
        )
        if needs_gap and out and out[-1].strip():
            out.append("")
        out.append(line)

    collapsed: list[str] = []
    for line in out:
        if not line.strip() and collapsed and not collapsed[-1].strip():
            continue
        collapsed.append(line)

    return "\n".join(collapsed).strip() + "\n"


def render(report: dict[str, Any]) -> str:
    ds = report["dataset"]
    imb = report["imbalance"]
    cov = report["time_coverage"]
    cens = report["censoring"]
    demo = report["leakage_demonstration"]
    sp = report["split"]
    sep = report["separability"]
    lk = report["leakage"]
    miss = report["missingness"]
    steps = {s["step"]: s for s in lk["steps"]}

    out: list[str] = []
    add = out.append

    add("# Data Audit\n")
    add(DISCLAIMER)
    add(
        "> Generated by `uv run mlservice data audit` from "
        "`reports/data_audit.json`. Do not edit by hand — regenerate it.\n"
    )
    add("---\n")

    # ---------------------------------------------------------------- summary
    add("## Summary\n")
    add(
        "The dataset survives the audit. It is genuinely hard, genuinely messy, "
        "and carries real time structure — which is what makes it worth "
        "operating a model on rather than merely fitting one. Four findings "
        "changed the pipeline:\n"
    )
    add(
        f"1. **Leakage, demonstrated rather than asserted.** Training on "
        f"{demo['numeric_columns_used']} post-origination columns reaches "
        f"**ROC-AUC {demo['roc_auc_with_leakage']}** against an honest ceiling near "
        f"{demo['honest_ceiling']}. Of the {demo['recoveries_positive_n']:,} loans with "
        f"`recoveries > 0`, **{_pct(demo['recoveries_positive_default_rate'])}** are "
        "defaults — recoveries is money clawed back *after* a default, so a non-zero "
        "value **is** the label.\n"
        f"2. **Right-censoring dominates the recent years.** "
        f"{cens['unresolved_pct_overall']}% of loans are still unresolved, and the "
        "resolved fraction collapses with recency. Requiring the full term to have "
        "elapsed moves the positive rate from **0.1998 to "
        f"{imb['positive_rate']}** — skipping the rule overstates default by 35% "
        "relative.\n"
        "3. **The label leaked back in as a feature.** `loan_status` is the column "
        "the target is derived from, so it maps one-to-one onto it. It survived the "
        "first pass because the data dictionary describes it as a loan attribute — "
        "which it is, right up until you make it the label.\n"
        "4. **The time column is a real date.** `issue_d` is an actual date, so "
        "the chronological split is correct by construction and needs no "
        "statistical argument that an ordering carries time signal.\n"
    )
    add("---\n")

    # ------------------------------------------------------------- 1. dataset
    add("## 1. The dataset\n")
    add("| | |\n|:--|:--|\n")
    add(f"| Rows (raw) | {ds['rows']:,} |\n")
    add(f"| Columns (raw) | {ds['columns']} |\n")
    add(f"| Issue dates | {cov['range']['start']} → {cov['range']['end']} |\n")
    add(f"| Rows after cleaning | {lk['rows_out']:,} ({lk['pct_removed']}% removed) |\n")
    add("| Borrower identity | **unavailable** — `member_id` is null for every row |\n")
    add(
        "\nThat last row is a limitation, not a detail. Repeat borrowers cannot be "
        "detected, so the same person may appear in both train and test, and the "
        "held-out numbers are inflated to whatever extent repeat borrowing occurs. "
        "Deduplicating by borrower is the standard defence and it is not "
        "and assert nobody straddled the split; here that is simply not possible.\n"
    )

    add("### Volume by year\n")
    add("| Year | Loans | Default rate |\n|:--|--:|--:|\n")
    for year, stats in sorted(cov["by_year"].items()):
        add(f"| {year} | {stats['n']:,} | {stats['positive_rate']:.4f} |\n")
    add(
        "\nThe book grew by three orders of magnitude across the period. Under a "
        "chronological split that means the training years are small and the test "
        "years are large, which is realistic — a model deployed in 2015 was trained "
        "on a business that barely resembled it.\n"
    )
    add("---\n")

    # ----------------------------------------------------------- 2. imbalance
    add("## 2. Class imbalance\n")
    add("| | |\n|:--|:--|\n")
    add(f"| Defaults | {imb['binary_positive']:,} |\n")
    add(f"| Repaid | {imb['binary_negative']:,} |\n")
    add(f"| Positive rate | **{imb['positive_rate']}** |\n")
    add(f"| Imbalance ratio | {imb['imbalance_ratio']}:1 |\n")
    add(f"\n{imb['interpretation']}\n")
    add("---\n")

    # ------------------------------------------------------------ 3. censoring
    add("## 3. Right-censoring — the most consequential rule\n")
    add(
        "Resolution is a function of age. A loan issued in December 2018 has not "
        "had time to default, so its absence of default is **not evidence of "
        "repayment**. Treating it as a negative teaches the model that recent "
        "loans are safe — which is a fact about when the file was exported, not "
        "about lending.\n"
    )
    add("| Issue year | Loans | Resolved | Default rate of resolved |\n|:--|--:|--:|--:|\n")
    for year, stats in sorted(cens["by_year"].items()):
        rate = stats["default_rate_of_resolved"]
        add(
            f"| {year} | {stats['n']:,} | {stats['resolved_pct']}% | "
            f"{rate if rate is not None else '—'} |\n"
        )
    add(f"\n{cens['interpretation']}\n")
    add(
        f"\n**The rule:** `{cens['rule']}`, with the observation window ending "
        f"{cens['observation_end']}. Stated, not tuned — a cut chosen to make the "
        "numbers look better is exactly what this audit exists to prevent.\n"
    )
    add("---\n")

    # -------------------------------------------------------------- 4. leakage
    add("## 4. Leakage\n")
    add("### 4.1 Post-origination columns — demonstrated\n")
    add(f"{demo['interpretation']}\n")
    add(
        f"\n{steps['drop_leaking_columns']['columns_dropped']} columns are dropped for "
        "this reason. They are enumerated in `configs/base.yaml` rather than inferred, "
        "because a heuristic like *drop anything correlated with the target* would "
        "also drop legitimately predictive features and could not explain itself.\n"
    )

    add("### 4.2 The label as a feature\n")
    tgt = steps["drop_target_source"]
    add(
        f"`{tgt['column']}` perfectly predicts the target: "
        f"**{tgt['perfectly_predicts_target']}**. It is the column the label is "
        "derived from.\n\n"
        "This is worth dwelling on. It survived the first version of the pipeline "
        "because the leakage list was written from the data dictionary, which "
        "describes `loan_status` as a loan attribute — and it is one, right up until "
        "you make it the label. **Deriving a target creates a leak that did not exist "
        "before**, so a leakage list cannot be written once and trusted.\n"
    )

    add("### 4.3 Unresolved is not negative\n")
    resolved = steps["resolve_label"]
    add(f"{resolved['rows_dropped']:,} loans were dropped for having no terminal outcome:\n\n")
    add("| Status | Loans |\n|:--|--:|\n")
    for status, n in sorted(resolved["dropped_by_status"].items(), key=lambda kv: -kv[1]):
        add(f"| {status} | {n:,} |\n")
    add(
        "\nA loan 90 days late will *probably* charge off, but probably is not a "
        "label. Encoding the guess would bake an assumption into the ground truth "
        "where nobody could see it.\n"
    )
    add("---\n")

    # ---------------------------------------------------------- 5. missingness
    add("## 5. Missingness\n")
    add(
        f"{miss['columns_with_any_missing']} columns have missing values; "
        f"{miss['columns_above_50pct']} are more than half missing and are dropped.\n"
    )
    add(
        "\nTwo kinds of absence, and they are treated differently:\n\n"
        "- **Structural** — Lending Club added fields over the years, so a column "
        "introduced in 2015 is null for every earlier loan. Under a chronological "
        "split that is a proxy for the era rather than the borrower, which is why "
        "anything above 50% missing is removed.\n"
        "- **Informative** — `mths_since_recent_inq` is null precisely when there has "
        "been no recent credit inquiry. That is a fact about the borrower, and a good "
        "one. Median imputation alone would convert *never* into *typical*, so the "
        "feature pipeline carries a missingness indicator alongside every numeric "
        "column.\n"
    )
    worst = list(miss["native_nan"].items())[:8]
    if worst:
        add("\n| Column | Missing | Likely reason |\n|:--|--:|:--|\n")
        for col, info in worst:
            add(f"| `{col}` | {info['pct']}% | {info['likely_reason']} |\n")
    add("---\n")

    # ----------------------------------------------------- 6. redundancy
    add("## 6. Constants and collinearity\n")
    red = steps["drop_constant_and_redundant"]
    add(
        f"**Constant:** {', '.join(f'`{c}`' for c in red['constant'])} — one value for "
        "every row. Zero information, and each costs a field in the serving contract.\n\n"
        f"**Redundant:** {', '.join(f'`{c}`' for c in red['redundant'])}. "
        "`fico_range_low` and `fico_range_high` correlate at **exactly 1.0** — they are "
        "two ends of a fixed-width band, so one is the other plus a constant. "
        "`funded_amnt` sits at 0.9989 against `loan_amnt`, because on a funded loan the "
        "amount requested is the amount funded. Keeping both halves of each pair gives "
        "a linear model two identical columns to split a coefficient across, inflating "
        "its variance and making the weights unreadable.\n"
    )
    hist = steps["derive_credit_history"]
    add(
        f"\n**Derived:** `earliest_cr_line` becomes `credit_history_months` "
        f"(median {hist['median_months']}). As shipped it is a date with 691 distinct "
        "values; as a categorical it would explode into hundreds of rare dummies "
        "encoding the era. Measured against the loan's own issue date it becomes how "
        "long the borrower has had credit — a real risk feature, and era-invariant.\n"
    )
    add("---\n")

    # -------------------------------------------------------- 7. separability
    add("## 7. Is the problem genuinely hard?\n")
    add(
        "An unconstrained decision tree is fitted deliberately, and the hope is that "
        "it does **badly**. The logic is inverted on purpose: a tree with no depth "
        "limit that still generalises would mean something is leaking.\n"
    )
    add("| | |\n|:--|:--|\n")
    add(f"| Train ROC-AUC | {sep['train_roc_auc']} |\n")
    add(f"| **Test ROC-AUC** | **{sep['test_roc_auc']}** |\n")
    add(f"| Tree depth | {sep['tree_depth']} |\n")
    add(f"| Leaves | {sep['n_leaves']:,} |\n")
    add(f"| Alarm (above {sep['alarm_threshold']}) | {sep['alarm_triggered']} |\n")
    add(
        "\nIt memorises the training set completely and retains almost nothing. "
        "That gap is the healthy result.\n"
    )
    add("---\n")

    # ------------------------------------------------------------- 8. baselines
    add("## 8. Baselines to beat\n")
    add("| Baseline | Accuracy | Recall | PR-AUC |\n|:--|--:|--:|--:|\n")
    for b in report["baselines"]:
        add(f"| `{b['name']}` | {b['accuracy']:.4f} | {b['recall']:.3f} | {b['pr_auc']:.4f} |\n")
    add(
        "\n**`heuristic_int_rate` is the one that matters.** `int_rate` is not a raw "
        "borrower attribute — it is the price Lending Club set *after* running their "
        "own underwriting model. So this baseline asks whether a new model beats the "
        "incumbent lender's judgment using a number available free at origination. "
        "A trained model that cannot clear it has not earned its deployment, "
        "monitoring and retraining infrastructure.\n"
    )
    add("---\n")

    # ----------------------------------------------------------------- 9. split
    add("## 9. The split\n")
    add(f"{sp['claim']}.\n")
    add("| Split | Rows | Positive rate | Ends |\n|:--|--:|--:|:--|\n")
    bounds = sp["date_boundaries"]
    add(
        f"| train | {sp['sizes']['train']:,} | {sp['positive_rate']['train']} | "
        f"{bounds['train_end']} |\n"
    )
    add(f"| val | {sp['sizes']['val']:,} | {sp['positive_rate']['val']} | {bounds['val_end']} |\n")
    add(
        f"| test | {sp['sizes']['test']:,} | {sp['positive_rate']['test']} | "
        f"{bounds['test_end']} |\n"
    )
    add(
        "\nCut on **month boundaries** rather than row positions: loans issued in the "
        "same month share a credit policy and a macro environment, so slicing through "
        "a month puts near-siblings on both sides. The realised fractions are "
        "therefore approximate rather than exactly 60/20/20, and are reported rather "
        "than assumed.\n"
    )
    for limitation in sp.get("limitations", []):
        add(f"\n> **Limitation.** {limitation}\n")
    add("---\n")

    # ------------------------------------------------------------- 10. subgroups
    add("## 10. Subgroups\n")
    add(
        "US credit data legally **excludes** race, gender and marital status, so "
        "there are no protected attributes to slice on directly. Fair-lending "
        "practice uses geography and socioeconomic position as proxies instead — "
        "which is what disparate-impact analysis has always done — and that is what "
        "these are.\n\n"
        "A disparity found here is not proof of discrimination. It is the signal "
        "that prompts someone to look.\n"
    )
    for dim, groups in report["subgroups"].items():
        usable = sum(1 for g in groups.values() if g["sufficient_for_analysis"])
        add(f"\n**`{dim}`** — {len(groups)} levels, {usable} with n ≥ 500.\n")
    add("---\n")

    add("## What this means for the model\n")
    add(
        "The ceiling is low and that is the point. A model that cannot be perfected "
        "is a model that must be carefully operated — monitored, gated, and "
        "rollback-tested — which is what the rest of this repository is about.\n\n"
        "Concretely, Phase 2 must:\n\n"
        "- report **PR-AUC** against the "
        f"{imb['positive_rate']} prevalence floor, never accuracy;\n"
        "- clear `heuristic_int_rate` with **non-overlapping confidence intervals**, "
        "not merely a higher point estimate;\n"
        "- report **calibration** alongside discrimination, because a probability "
        "that is acted on must mean what it says;\n"
        "- report **subgroup performance openly**, including where it is "
        "unflattering.\n"
    )

    return _normalise_markdown("".join(out))


def render_to_file(source: Path | None = None, target: Path | None = None) -> Path:
    source = source or (PROJECT_ROOT / "reports" / "data_audit.json")
    target = target or (PROJECT_ROOT / "docs" / "DATA_AUDIT.md")

    report = json.loads(source.read_text(encoding="utf-8"))
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render(report), encoding="utf-8", newline="\n")

    log.info("data_audit_rendered", source=str(source), target=str(target))
    return target


__all__ = ["render", "render_to_file"]
