"""Render ``docs/DATA_AUDIT.md`` from ``reports/data_audit.json``.

Generated rather than hand-written so the document cannot disagree with the
code. Every number below traces to a value the audit actually computed.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from mlservice.config import PROJECT_ROOT
from mlservice.logging_ import get_logger

log = get_logger(__name__)

DISCLAIMER = (
    "> **NOT FOR CLINICAL USE.** This document reports an engineering data "
    "audit. Nothing in it is clinically validated or fit to inform patient "
    "care.\n"
)


def _pct(x: float) -> str:
    return f"{x * 100:.2f}%"


def _normalise_markdown(text: str) -> str:
    """Insert the blank lines markdown needs, without breaking tables.

    Blocks are appended piecemeal above, so headings and tables can end up
    flush against the preceding line. A heading or a table that is not preceded
    by a blank line fails to render on several markdown engines, GitHub's
    included.

    Naively joining blocks with a blank line is *wrong* — table rows are
    appended one at a time, and separating them would destroy the table. So the
    rule is applied per line, with consecutive ``|`` rows kept together.
    """
    lines = text.splitlines()
    out: list[str] = []

    for line in lines:
        previous = out[-1] if out else ""
        starts_heading = line.startswith("#")
        starts_table = line.startswith("|") and not previous.startswith("|")
        # A table must also be *closed* by a blank line, or the prose that
        # follows gets absorbed into the final row.
        ends_table = previous.startswith("|") and not line.startswith("|")
        needs_gap = (
            (starts_heading or starts_table or ends_table)
            and previous.strip() != ""
            and line.strip() != ""
        )

        if needs_gap:
            out.append("")
        out.append(line)

        # A heading must also be followed by a blank line.
        if starts_heading:
            out.append("")

    # Collapse any run of blank lines to one.
    collapsed: list[str] = []
    for line in out:
        if line.strip() == "" and collapsed and collapsed[-1].strip() == "":
            continue
        collapsed.append(line)

    return "\n".join(collapsed).strip() + "\n"


def render(report: dict[str, Any]) -> str:
    ds = report["dataset"]
    imb = report["imbalance"]
    proxy = report["time_proxy"]
    cens = report["censoring"]
    sp = report["split"]
    sep = report["separability"]
    lk = report["leakage"]
    miss = report["missingness"]

    steps = {s["step"]: s for s in lk["steps"]}
    expired, hospice = steps["exclude_expired"], steps["exclude_hospice"]
    first_enc, dropped = steps["first_encounter_only"], steps["drop_columns"]

    out: list[str] = []
    add = out.append

    add("# Data Audit\n")
    add(DISCLAIMER)
    add(
        "> Generated by `uv run mlservice data audit` from "
        "`reports/data_audit.json`. Do not edit by hand — regenerate it.\n"
    )
    add("---\n")

    # ---------------------------------------------------------------- summary
    add("## Summary\n")
    add(
        "The dataset survives the audit. It is genuinely hard, genuinely messy, "
        "and carries real time structure — which is what makes it worth "
        "operating a model on. Four findings changed the pipeline:\n"
    )
    add(
        f"1. **A deterministic label leak.** {expired['n_rows']:,} expired-discharge "
        f"encounters with **{expired['n_positive']} positives**. Removed.\n"
        f"2. **The time proxy holds.** {proxy['n_trending']}/{proxy['n_signals']} "
        "independent signals shift monotonically across `encounter_id`, including "
        "a dated pharmacovigilance event. The split can honestly be called "
        "chronological.\n"
        f"3. **Right-censoring at the tail.** First-encounter positive rate collapses "
        f"{abs(cens['final_bin_relative_drop']) * 100:.0f}% in the final 5% of the "
        "ordering — labels are missing, not negative. A censoring buffer now "
        "discards it.\n"
        f"4. **`payer_code` is time-confounded**, not merely missing. Dropped.\n"
    )
    add("---\n")

    # ------------------------------------------------------------ the dataset
    add("## 1. The dataset\n")
    add(
        f"| | |\n|:--|:--|\n"
        f"| Rows | {ds['rows']:,} |\n"
        f"| Columns | {ds['columns']} |\n"
        f"| Unique patients | {ds['unique_patients']:,} |\n"
        f"| Encounters per patient | {ds['encounters_per_patient']} |\n"
    )
    add(
        "Diabetes 130-US Hospitals (UCI #296), 1999–2008. Inclusion criteria are "
        "non-trivial: inpatient admission, documented diabetes diagnosis, 1–14 day "
        "stay, labs performed, medications administered.\n"
    )

    # --------------------------------------------------------------- imbalance
    add("## 2. Class imbalance\n")
    add(
        "| Class | Count |\n|:--|--:|\n"
        + "".join(f"| `{k}` | {v:,} |\n" for k, v in imb["raw_classes"].items())
    )
    add(
        f"\nBinary task is `<30` vs rest: **{imb['positive_rate'] * 100:.2f}% positive**, "
        f"an imbalance ratio of {imb['imbalance_ratio']}:1.\n"
    )
    add(f"> {imb['interpretation']}\n")

    # -------------------------------------------------------------- missingness
    add("## 3. Missingness\n")
    add(
        "Two distinct kinds, handled differently because they mean different "
        "things. Missing values are encoded as a literal `?`, so anything "
        "counting nulls naively reports zero missingness and is wrong.\n"
    )
    add("### Sentinel `?` — not recorded\n")
    add("| Column | Missing | % |\n|:--|--:|--:|\n")
    for col, d in list(miss["sentinel_missing"].items())[:8]:
        add(f"| `{col}` | {d['n']:,} | {d['pct']}% |\n")
    add("\n### Native `NaN` — test not ordered\n")
    add("| Column | Missing | % | Meaning |\n|:--|--:|--:|:--|\n")
    for col, d in miss["native_nan"].items():
        add(f"| `{col}` | {d['n']:,} | {d['pct']}% | {d['meaning']} |\n")
    add(
        "\nThese are **not** missing at random. Whether a clinician ordered an "
        "HbA1c is a clinical decision and therefore informative. They become an "
        "explicit `NotMeasured` category — imputing them would destroy real "
        "signal and invent a measurement that was never taken.\n"
    )
    add(
        f"\n**Zero-variance columns:** "
        f"{', '.join('`' + c + '`' for c in miss['zero_variance_columns'])} — "
        "constant across every row, so they cannot contribute to any model.\n"
    )

    # ------------------------------------------------------------------ leakage
    add("## 4. Leakage hunt\n")
    add("### 4.1 Expired discharges — genuine leakage\n")
    add(
        f"`discharge_disposition_id` in {expired['codes']} means the patient died.\n\n"
        f"**{expired['n_rows']:,} such encounters contain {expired['n_positive']} "
        "positive labels.** Not few — *zero*. A dead patient cannot be readmitted, "
        "so the label is deterministic and a model would learn "
        "`died → not readmitted` directly from the discharge code.\n"
    )
    add("\n### 4.2 Hospice discharges — excluded, but not leakage\n")
    add(
        f"Codes {hospice['codes']} are hospice. These are **not** deterministic: "
        f"{hospice['n_positive']} of {hospice['n_rows']:,} are positive "
        f"({_pct(hospice['positive_rate'])}), so hospice patients genuinely are "
        "readmitted.\n\n"
        "They are excluded on clinical-relevance grounds — readmission is not a "
        "meaningful quality signal in end-of-life care — **not** as leakage. "
        "Conflating the two would overstate the finding.\n"
    )
    add("\n### 4.3 Patient overlap across splits\n")
    add(
        f"{ds['rows']:,} encounters span {ds['unique_patients']:,} patients, so the "
        "same patient can land on both sides of any split. Keeping only each "
        f"patient's first encounter removes {first_enc['rows_removed']:,} rows "
        f"({first_enc['rows_before']:,} → {first_enc['rows_after']:,}).\n\n"
        "This costs the prior-utilisation richness of repeat visits, which is a "
        "real loss. It is accepted because the alternative — a held-out estimate "
        "inflated by memorised patient idiosyncrasy — is worse.\n"
    )
    add("\n### 4.4 Columns dropped\n")
    add("| Column | Reason |\n|:--|:--|\n")
    for col, reason in dropped["columns"].items():
        add(f"| `{col}` | {reason} |\n")

    # -------------------------------------------------------------- time proxy
    add("\n## 5. Temporal proxy verification\n")
    add(
        "**This dataset has no timestamp column.** Not a missing one — none "
        "exists. The only time signal is the ordering of `encounter_id`. "
        "Claiming 'temporal validation' without evidence would be an unearned "
        "claim, so the proxy was tested before being trusted.\n"
    )
    add(
        "\n**Test:** clinical practice change is *directional* — a drug is "
        "adopted, a field starts being captured — whereas a meaningless row "
        "ordering produces non-monotonic noise. Spearman rank correlation "
        f"across {proxy.get('n_deciles', 10)} deciles "
        "distinguishes them.\n"
    )
    add(
        f"\n**Criteria:** |ρ| > {proxy['criteria']['min_abs_rho']} and "
        f"p < {proxy['criteria']['max_p_value']}, with at least "
        f"{proxy['threshold']} signals trending.\n\n"
    )
    add("| Signal | First decile | Last decile | Δ | ρ | p | Trends |\n")
    add("|:--|--:|--:|--:|--:|--:|:--:|\n")
    for s in proxy["signals"]:
        mark = "**yes**" if s["trends"] else "no"
        add(
            f"| {s['name']} | {s['first_decile']:.3f} | {s['last_decile']:.3f} | "
            f"{s['delta']:+.3f} | {s['spearman_rho']:+.3f} | {s['p_value']:.5f} | {mark} |\n"
        )
    add(
        f"\n**Result: {proxy['n_trending']}/{proxy['n_signals']} trending — "
        f"{'PASSED' if proxy['passed'] else 'FAILED'}.**\n"
    )

    rosi = proxy["discontinuity_rosiglitazone"]
    add("\n### 5.1 The strongest evidence: a dated external event\n")
    add(
        "Trend tests show the ordering carries time signal. A *discontinuity* "
        "does something stronger — it dates the ordering against the real world, "
        "which is a prediction that could have failed.\n"
    )
    add(
        f"\nRosiglitazone prescribing holds steady, then drops "
        f"**{abs(rosi['largest_drop_pct_points']):.1f} percentage points in a single "
        f"bin** at the {rosi['percentile_of_ordering']}th percentile of the ordering "
        f"— **{rosi['ratio_to_typical_change']}× larger** than any other "
        "bin-to-bin change.\n"
    )
    add(
        "\nPioglitazone — the competing drug in the same class — is unaffected, so "
        "this is drug-specific, not a general recording change.\n"
    )
    add(
        "\nThat is the Avandia collapse: Nissen & Wolski's NEJM meta-analysis "
        "(May 2007) linking rosiglitazone to myocardial infarction, followed by "
        "an FDA black-box warning that November. Prescribing halved and stayed "
        "down.\n"
    )
    add(
        "\n**The ordering reproduces a dated pharmacovigilance event.** That "
        "places the 80th percentile of `encounter_id` at roughly mid-2007 and "
        "makes the chronological claim about as well-evidenced as it can be "
        "without a date column.\n"
    )

    # --------------------------------------------------------------- censoring
    add("\n## 6. Right-censoring at the end of the window\n")
    add(
        "A first encounter is labelled positive only if a *subsequent* encounter "
        "exists in the data. Near the end of collection those later encounters "
        "are unobserved — so the label is **missing, not negative**.\n"
    )
    add(
        f"\nThe effect appears only after first-encounter deduplication: across "
        "all encounters the positive rate is flat over the period. After "
        f"deduplication it sits at {_pct(cens['stable_rate_first_80pct'])} through "
        f"the first 80% and falls to {_pct(cens['final_bin_rate'])} in the final "
        f"5% — a **{abs(cens['final_bin_relative_drop']) * 100:.0f}% relative "
        "collapse**.\n"
    )
    add(
        f"\n**Mitigation:** the final {cens['buffer_fraction'] * 100:.0f}% of the "
        "ordering is discarded as a censoring buffer before splitting. Without "
        "it that region lands entirely in the test set, depressing every "
        "held-out metric for a reason unrelated to the model — and Phase 6 drift "
        "monitoring would chase an artifact of data collection.\n"
    )

    # ------------------------------------------------------------------- split
    add("\n## 7. The split\n")
    add(f"**Claim supported by the evidence:** {sp['claim']}\n")
    add(
        f"\n| Split | Rows | Positive rate |\n|:--|--:|--:|\n"
        f"| Train | {sp['sizes']['train']:,} | {_pct(sp['positive_rate']['train'])} |\n"
        f"| Validation | {sp['sizes']['val']:,} | {_pct(sp['positive_rate']['val'])} |\n"
        f"| Test | {sp['sizes']['test']:,} | {_pct(sp['positive_rate']['test'])} |\n"
    )
    add(
        "\nSplit by position in `encounter_id` order, never at random. A random "
        "split on time-structured data leaks the future into training: the model "
        "would see post-2007 prescribing patterns while being evaluated on them.\n"
    )
    add(
        "\n**A residual gradient remains** after the censoring buffer "
        f"({_pct(sp['positive_rate']['train'])} → {_pct(sp['positive_rate']['test'])}). "
        "Part is real prior-probability shift; part is residual censoring the "
        "buffer does not fully remove. It is reported rather than smoothed away, "
        "and Phase 2 must not attribute it to model quality.\n"
    )

    # ------------------------------------------------------------ separability
    add("\n## 8. Separability sanity check\n")
    add(
        "Deliberately inverted logic: an unconstrained decision tree is fitted "
        "*hoping it does badly*. On the widely-circulated synthetic "
        "symptom-to-disease datasets a tree like this reaches ~100% AUC, which "
        "reveals the data is trivially separable and worthless for demonstrating "
        "anything.\n"
    )
    add(
        f"\n| | |\n|:--|--:|\n"
        f"| Train ROC-AUC | {sep['train_roc_auc']} |\n"
        f"| **Test ROC-AUC** | **{sep['test_roc_auc']}** |\n"
        f"| Tree depth | {sep['tree_depth']} |\n"
        f"| Leaves | {sep['n_leaves']:,} |\n"
        f"| Alarm threshold | {sep['alarm_threshold']} |\n"
        f"| Alarm triggered | {'YES — investigate' if sep['alarm_triggered'] else 'no'} |\n"
    )
    add(f"\n> {sep['interpretation']}\n")

    # --------------------------------------------------------------- baselines
    add("\n## 9. Baselines — the floor to beat\n")
    add("| Baseline | Accuracy | Recall | PR-AUC | Brier |\n|:--|--:|--:|--:|--:|\n")
    for b in report["baselines"]:
        add(
            f"| {b['name']} | {b['accuracy']:.4f} | {b['recall']:.4f} | "
            f"{b['pr_auc']:.4f} | {b['brier']:.4f} |\n"
        )
    majority = next(b for b in report["baselines"] if b["name"] == "majority_class")
    heuristic = next(b for b in report["baselines"] if b["name"].startswith("heuristic"))
    add(
        f"\n**The accuracy trap, made concrete.** The majority-class baseline scores "
        f"**{majority['accuracy']:.2%} accuracy with {majority['recall']:.0%} recall** — "
        "it never identifies a single at-risk patient. Any project reporting "
        "accuracy on this task is reporting that number.\n"
    )
    if heuristic.get("pr_auc_ci"):
        lo, hi = heuristic["pr_auc_ci"]
        add(
            f"\n**The bar that matters** is the one-feature heuristic: PR-AUC "
            f"{heuristic['pr_auc']:.4f} (95% CI {lo:.4f}–{hi:.4f}), available at "
            "admission with no model at all. A trained model must clear this with "
            "non-overlapping intervals to justify the cost of deploying, "
            "monitoring and retraining it.\n"
        )

    # --------------------------------------------------------------- subgroups
    add("\n## 10. Subgroup populations\n")
    add(
        "Established before any modelling, so Phase 2's performance breakdown "
        "reports only on subgroups large enough to say something. A disparity "
        "computed on 40 patients is noise presented as a finding.\n"
    )
    for dim, groups in report["subgroups"].items():
        add(f"\n**`{dim}`**\n\n| Group | n | % | Positive rate | Analysable |\n")
        add("|:--|--:|--:|--:|:--:|\n")
        for name, d in sorted(groups.items(), key=lambda kv: -kv[1]["n"]):
            ok = "yes" if d["sufficient_for_analysis"] else "**no (n<500)**"
            add(f"| {name} | {d['n']:,} | {d['pct']}% | {_pct(d['positive_rate'])} | {ok} |\n")

    add("\n---\n")
    add("## What this means for Phase 2\n")
    add(
        "- Report **PR-AUC** as the headline against a "
        f"{sp['positive_rate']['test'] * 100:.2f}% test prevalence floor. Never accuracy.\n"
        "- Beat the one-feature heuristic with **non-overlapping confidence "
        "intervals**, or the model has not earned its infrastructure.\n"
        "- Do not attribute the train→test positive-rate gradient to model "
        "quality; it is partly a property of the data.\n"
        "- Report subgroup performance only where n ≥ 500, and report it even "
        "when unflattering.\n"
        "- Expect modest numbers. The published ceiling is ROC-AUC 0.65–0.68. "
        "That is the point of this project, not a shortfall.\n"
    )
    return _normalise_markdown("".join(out))


def render_to_file(report_path: Path | None = None, out_path: Path | None = None) -> Path:
    report_path = report_path or PROJECT_ROOT / "reports" / "data_audit.json"
    out_path = out_path or PROJECT_ROOT / "docs" / "DATA_AUDIT.md"
    if not report_path.is_file():
        raise FileNotFoundError(
            f"{report_path} not found. Run `uv run mlservice data audit` first."
        )
    report = json.loads(report_path.read_text(encoding="utf-8"))
    out_path.write_text(render(report), encoding="utf-8")
    log.info("audit_doc_rendered", path=str(out_path))
    return out_path


__all__ = ["render", "render_to_file"]
