"""Render ``docs/MODEL_CARD.md`` from ``reports/training_summary.json``.

Generated, not written by hand, for the same reason the data audit is: a model
card transcribed manually goes stale the first time anyone retrains, and a stale
model card is worse than none — it states numbers the deployed model does not
produce.

Follows the Mitchell et al. (2019) structure, with out-of-scope use and
subgroup performance treated as mandatory rather than optional sections.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from mlservice.config import PROJECT_ROOT, get_settings, get_thresholds
from mlservice.logging_ import get_logger
from mlservice.models.evaluate import TARGET_RECALL

log = get_logger(__name__)


def _pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def _normalise_markdown(text: str) -> str:
    """Blank lines where markdown needs them, without splitting tables apart."""
    out: list[str] = []
    for line in text.splitlines():
        previous = out[-1] if out else ""
        heading = line.startswith("#")
        table_start = line.startswith("|") and not previous.startswith("|")
        table_end = previous.startswith("|") and not line.startswith("|")
        if (heading or table_start or table_end) and previous.strip() and line.strip():
            out.append("")
        out.append(line)
        if heading:
            out.append("")

    collapsed: list[str] = []
    for line in out:
        if not line.strip() and collapsed and not collapsed[-1].strip():
            continue
        collapsed.append(line)
    return "\n".join(collapsed).strip() + "\n"


def render(summary: dict[str, Any], audit: dict[str, Any]) -> str:
    settings = get_settings()
    thresholds = get_thresholds().model_dump()

    champ = next(c for c in summary["candidates"] if c["name"] == summary["champion"])
    sub = champ["subgroups"]
    cal = champ["calibration"]
    heuristic = next(b for b in audit["baselines"] if b["name"].startswith("heuristic"))
    majority = next(b for b in audit["baselines"] if b["name"] == "majority_class")

    out: list[str] = []
    add = out.append

    add("# Model Card — Hospital Readmission Risk\n")
    add(
        "> ## NOT FOR CLINICAL USE\n>\n"
        "> This model is an **engineering demonstration of ML operations**. It is\n"
        "> not a medical device, has never been clinically validated, and must\n"
        "> never inform patient care. It is trained on a public 1999–2008 research\n"
        "> dataset that does not reflect current clinical practice.\n"
    )
    add(
        "> Generated by `uv run mlservice train run` from "
        "`reports/training_summary.json`. Do not edit by hand — regenerate it.\n"
    )
    add("---\n")

    # ------------------------------------------------------------------ details
    add("## Model details\n")
    add(
        f"| | |\n|:--|:--|\n"
        f"| Name | `{settings.model.name}` |\n"
        f"| Version | {summary.get('registered_version') or 'unregistered'} |\n"
        f"| Type | {summary['champion']} — regularised logistic regression |\n"
        f"| Calibration | {summary['calibration_method']}, fitted on validation |\n"
        f"| Decision threshold | {summary['champion_threshold']:.4f} |\n"
        f"| Feature schema hash | `{summary['feature_schema_hash']}` |\n"
        f"| Training rows | {summary['splits']['train']:,} |\n"
        f"| Licence | MIT (code); CC BY 4.0 (data) |\n"
    )

    # ------------------------------------------------------------- intended use
    add("## Intended use\n")
    add(
        "**Intended:** demonstrating a production ML lifecycle — serving, "
        "monitoring, drift detection, calibration-gated retraining and rollback. "
        "The model exists so that there is something real to operate.\n"
    )
    add("### Out-of-scope use\n")
    add(
        "Stated at equal prominence because it is the more important half:\n\n"
        "- **Any clinical decision.** Not validated, not a device, not lawful to "
        "use as one.\n"
        "- **Individual patient risk communication.** At the operating threshold "
        f"{_pct(1 - champ['precision'])} of flagged patients are not readmitted "
        "within 30 days.\n"
        "- **Resource allocation or triage.** The subgroup disparities below make "
        "this actively harmful.\n"
        "- **Any population outside the training distribution** — US inpatient "
        "diabetes encounters, 1999–2008, 1–14 day stays.\n"
        "- **Transfer to current practice.** Diabetes care has changed "
        "substantially since 2008; the audit detected the 2007 rosiglitazone "
        "withdrawal *inside* the training period.\n"
    )

    # ----------------------------------------------------------------- training
    add("## Training data\n")
    add(
        f"Diabetes 130-US Hospitals (UCI #296) — {audit['dataset']['rows']:,} encounters "
        f"across 130 hospitals, 1999–2008. After cleaning: "
        f"{audit['leakage']['rows_out']:,} rows "
        f"({audit['leakage']['pct_removed']}% removed).\n"
    )
    add(
        "Exclusions and their reasons are in "
        "[DATA_AUDIT.md](DATA_AUDIT.md). The load-bearing ones:\n\n"
        "- **Expired discharges removed** — 1,652 encounters with exactly zero "
        "positive labels. A deterministic leak.\n"
        "- **First encounter per patient only** — otherwise the same patient "
        "appears on both sides of the split.\n"
        "- **`payer_code` dropped** — time-confounded, not merely missing.\n"
        "- **Final 5% of the ordering dropped** — right-censoring makes those "
        "labels missing rather than negative.\n"
    )
    add(
        f"**Split:** {summary['splits']['train']:,} train / "
        f"{summary['splits']['val']:,} validation / {summary['splits']['test']:,} test, "
        "chronological on a verified `encounter_id` proxy "
        "([ADR 0004](DECISIONS/0004-temporal-split-proxy.md)). **No timestamps "
        "exist in this dataset**; the ordering is a proxy that was tested before "
        "being trusted.\n"
    )

    # ------------------------------------------------------------------ metrics
    add("## Performance\n")
    add(
        "PR-AUC is the headline. At a "
        f"{champ['prevalence'] * 100:.2f}% positive rate ROC-AUC is dominated by "
        "the large negative class and moves without changing what happens to the "
        "patients who are actually readmitted.\n"
    )
    pr, roc, br = champ["pr_auc"], champ["roc_auc"], champ["brier"]
    add(
        f"| Metric | Value | 95% CI |\n|:--|--:|:--|\n"
        f"| **PR-AUC** | **{pr['point']:.4f}** | [{pr['lower']:.4f}, {pr['upper']:.4f}] |\n"
        f"| ROC-AUC | {roc['point']:.4f} | [{roc['lower']:.4f}, {roc['upper']:.4f}] |\n"
        f"| Brier | {br['point']:.4f} | [{br['lower']:.4f}, {br['upper']:.4f}] |\n"
        f"| ECE (10 bins) | {cal['ece']:.4f} | — |\n"
        f"| MCE (worst bin) | {cal['mce']:.4f} | — |\n"
    )
    add("### Against the baselines it must beat\n")
    hl, hu = heuristic["pr_auc_ci"]
    overlaps = not (pr["upper"] < hl or hu < pr["lower"])
    add(
        f"| Model | PR-AUC | 95% CI |\n|:--|--:|:--|\n"
        f"| Prevalence floor | {champ['prevalence']:.4f} | — |\n"
        f"| `number_inpatient` heuristic | {heuristic['pr_auc']:.4f} | [{hl:.4f}, {hu:.4f}] |\n"
        f"| **This model** | **{pr['point']:.4f}** | [{pr['lower']:.4f}, {pr['upper']:.4f}] |\n"
    )
    add(
        f"The intervals **{'overlap' if overlaps else 'do not overlap'}**, so the "
        f"model {'has not' if overlaps else 'has'} demonstrably beaten a "
        "one-feature heuristic available at admission with no model at all. That "
        "was the bar for justifying the serving, monitoring and retraining "
        "infrastructure.\n"
    )
    add(
        f"For contrast, the majority-class baseline scores "
        f"**{majority['accuracy']:.1%} accuracy with {majority['recall']:.0%} recall.** "
        "This is why accuracy is not reported as a headline metric.\n"
    )

    # --------------------------------------------------------------- operating
    add("## Operating point, stated honestly\n")
    add(
        f"The threshold ({summary['champion_threshold']:.4f}) was chosen **on "
        f"validation** to reach {_pct(TARGET_RECALL)} "
        "recall. On the held-out test split:\n"
    )
    add(
        f"| | |\n|:--|--:|\n"
        f"| Recall | {champ['recall']:.3f} |\n"
        f"| Precision | {champ['precision']:.3f} |\n"
        f"| Patients flagged | {_pct(champ['flagged_rate'])} |\n"
        f"| Lift over prevalence | {champ['lift_over_prevalence']}× |\n"
        f"| True positives | {champ['true_positives']:,} |\n"
        f"| False positives | {champ['false_positives']:,} |\n"
        f"| False negatives | {champ['false_negatives']:,} |\n"
    )
    add(
        f"**Read those numbers plainly.** To catch {champ['recall']:.0%} of "
        f"readmissions the model flags {_pct(champ['flagged_rate'])} of all "
        f"patients, and {_pct(1 - champ['precision'])} of those flags are wrong. "
        f"It produces {champ['false_positives']:,} false alarms for "
        f"{champ['true_positives']:,} true ones. That is the real trade-off at "
        "this prevalence, and no threshold choice escapes it — it is a property "
        "of the problem, not a defect of the model.\n"
    )
    add(
        "Recall on test "
        f"({champ['recall']:.3f}) also fell short of the validation target "
        f"({champ['threshold_info']['achieved_recall']:.3f}). A threshold tuned on "
        "one time period does not transfer perfectly to the next — which is "
        "precisely the behaviour the monitoring in Phase 6 exists to detect.\n"
    )

    # ------------------------------------------------------------- calibration
    add("## Calibration\n")
    add(
        "Calibration is a **deployment gate** in this project, not a report "
        "([ADR 0002](DECISIONS/0002-calibration-as-deployment-gate.md)). A "
        "challenger that ranks better but calibrates worse is blocked.\n"
    )
    gate = thresholds["promotion"]["calibration"]
    add(
        f"| | Value | Gate | Status |\n|:--|--:|--:|:--|\n"
        f"| ECE (10 bins) | {cal['ece']:.4f} | ≤ {gate['max_ece']} | "
        f"{'PASS' if cal['ece'] <= gate['max_ece'] else 'FAIL'} |\n"
        f"| Brier | {br['point']:.4f} | — | — |\n"
        f"| MCE (worst bin) | {cal['mce']:.4f} | — | reported, not gated |\n"
    )
    # Read the ECE/MCE disagreement out of the run rather than hardcoding it.
    # A generated card that states last month's numbers is worse than no card.
    scored = [c for c in summary["candidates"] if c.get("calibration", {}).get("ece")]
    best_ece = min(scored, key=lambda c: c["calibration"]["ece"]) if scored else None
    worst_mce = max(scored, key=lambda c: c["calibration"]["mce"]) if scored else None

    add(
        "MCE is reported alongside ECE because they can disagree sharply, and a "
        "single number would hide it.\n"
    )
    if best_ece and worst_mce and best_ece["name"] == worst_mce["name"]:
        add(
            f"\nIn this run `{best_ece['name']}` held the **best** ECE "
            f"({best_ece['calibration']['ece']:.4f}) *and* the **worst** MCE "
            f"({worst_mce['calibration']['mce']:.4f}) — one probability bin was "
            "badly wrong while the count-weighted average looked healthy.\n"
        )
    elif best_ece and worst_mce:
        add(
            f"\nIn this run the best ECE was `{best_ece['name']}` "
            f"({best_ece['calibration']['ece']:.4f}) while the worst MCE was "
            f"`{worst_mce['name']}` ({worst_mce['calibration']['mce']:.4f}).\n"
        )
    add("![Reliability diagram](images/reliability_test.png)\n")

    # --------------------------------------------------------------- subgroups
    add("## Subgroup performance\n")
    add(
        "Reported for every subgroup above n="
        f"{sub['min_subgroup_n']}, **including where the results are "
        "unflattering.** Selective reporting would be worse than no fairness "
        "analysis, because it implies a check that was not really performed.\n"
    )
    add(
        "The same threshold is applied to every group. Per-group thresholds "
        "would improve these numbers and would mean treating patients "
        "differently by demographics — the thing this analysis exists to "
        "detect, not to implement.\n"
    )

    for dim in ("race", "gender", "age"):
        rows = [g for g in sub["groups"] if g["dimension"] == dim]
        if not rows:
            continue
        add(f"### `{dim}`\n")
        add("| Group | n | Positives | Recall | Precision | Gap vs overall | Analysed |\n")
        add("|:--|--:|--:|--:|--:|--:|:--:|\n")
        for g in sorted(rows, key=lambda r: -r["n"]):
            mark = "yes" if g["sufficient"] else "**no — n too small**"
            add(
                f"| {g['group']} | {g['n']:,} | {g['n_positive']:,} | "
                f"{g['recall']:.3f} | {g['precision']:.3f} | "
                f"{g['recall_gap_vs_overall']:+.3f} | {mark} |\n"
            )

    worst = max(
        (g for g in sub["groups"] if g["sufficient"]),
        key=lambda g: -g["recall_gap_vs_overall"],
    )
    add("### The disparities, stated without softening\n")

    # Derived from the run, never hardcoded: which group is worst is an
    # empirical result that a retrain can change, and a card asserting last
    # month's disparity would be actively misleading.
    def spread(dimension: str) -> tuple[dict[str, Any], dict[str, Any]] | None:
        eligible = [g for g in sub["groups"] if g["dimension"] == dimension and g["sufficient"]]
        if len(eligible) < 2:
            return None
        return (
            min(eligible, key=lambda g: g["recall"]),
            max(eligible, key=lambda g: g["recall"]),
        )

    for dimension, gloss in (
        (
            "race",
            "The model misses a substantially larger share of readmissions in the lower group.",
        ),
        ("gender", "The gap here is small relative to the other dimensions."),
        (
            "age",
            "The model is markedly better at identifying at-risk older patients than middle-aged ones.",
        ),
    ):
        pair = spread(dimension)
        if not pair:
            continue
        low, high = pair
        add(
            f"**`{dimension}`.** Recall runs from **{low['recall']:.3f}** "
            f"({low['group']}, n={low['n']:,}) to **{high['recall']:.3f}** "
            f"({high['group']}, n={high['n']:,}) — a spread of "
            f"{(high['recall'] - low['recall']) * 100:.1f} percentage points across "
            f"subgroups large enough to analyse. {gloss}\n"
        )
    add(
        "**A plausible mechanism, not a proven one.** The strongest features are "
        "prior-utilisation counts. Any group whose earlier care was delivered "
        "outside this hospital network, or recorded less completely, carries "
        "artificially low prior-utilisation values and is therefore "
        "systematically under-flagged. If that is the mechanism, the disparity "
        "originates in the data-generating process — which means it would not be "
        "fixed by reweighting the model, and could be made invisible rather than "
        "absent by doing so.\n"
    )
    add(
        f"**Worst analysable gap: {worst['recall_gap_vs_overall']:+.3f} "
        f"({worst['dimension']}={worst['group']}).** The Phase 7 promotion gate "
        "blocks any challenger that widens this by more than 20% relative — the "
        "gate is anchored to the incumbent because no absolute fairness constant "
        "would be defensible on this data, and inventing one implies a guarantee "
        "the evaluation cannot support.\n"
    )

    # ------------------------------------------------------------- limitations
    add("## Limitations\n")
    add(
        "- **No timestamps exist.** The chronological split rests on an\n"
        "  `encounter_id` proxy, verified but still a proxy.\n"
        "- **A positive-rate gradient survives the censoring buffer** "
        f"({audit['split']['positive_rate']['train'] * 100:.2f}% train → "
        f"{audit['split']['positive_rate']['test'] * 100:.2f}% test). Part real "
        "shift, part residual censoring; they cannot be separated without dates.\n"
        "- **Modest discrimination by design.** The published ceiling is ROC-AUC "
        "0.65–0.68. This project treats a well-operated modest model as the goal.\n"
        "- **Single-network, 1999–2008, US inpatient diabetes encounters only.**\n"
        "- **Documented subgroup disparities** that are not mitigated in the "
        "model, only measured and gated against worsening.\n"
        "- **Prior-utilisation dependence** makes the model sensitive to "
        "record completeness, which is itself unevenly distributed.\n"
    )

    # ----------------------------------------------------------------- selection
    add("## How this model was selected\n")
    rationale = summary["selection_rationale"]
    add(f"**Rule:** {rationale['rule']}.\n")
    add("| Candidate | PR-AUC | 95% CI | ECE | Chosen |\n|:--|--:|:--|--:|:--:|\n")
    for c in summary["candidates"]:
        p = c["pr_auc"]
        e = c["calibration"].get("ece") if c.get("calibration") else None
        mark = "**yes**" if c["name"] == summary["champion"] else ""
        add(
            f"| {c['name']} | {p['point']:.4f} | [{p['lower']:.4f}, {p['upper']:.4f}] | "
            f"{e:.4f} | {mark} |\n"
            if e is not None
            else f"| {c['name']} | {p['point']:.4f} | [{p['lower']:.4f}, {p['upper']:.4f}] | — | {mark} |\n"
        )
    add(f"\n{rationale['note']}\n")
    add(
        "**XGBoost was not tried.** It was admitted only on audit evidence of "
        "non-linear structure worth the operational cost, and the audit produced "
        "the opposite: an unconstrained decision tree — able to represent "
        "arbitrary interactions — reached 0.519 test ROC-AUC. The shallow random "
        "forest here likewise failed to beat logistic regression. There is no "
        "unexploited non-linear signal to buy. See "
        "[ADR 0005](DECISIONS/0005-model-selection.md).\n"
    )

    add("## Citation\n")
    add(
        "> Strack, B., DeShazo, J.P., Gennings, C., Olmo, J.L., Ventura, S.,\n"
        "> Cios, K.J., Clore, J.N. (2014). *Impact of HbA1c Measurement on\n"
        "> Hospital Readmission Rates.* BioMed Research International.\n"
    )
    return _normalise_markdown("".join(out))


def render_to_file(out_path: Path | None = None) -> Path:
    reports = PROJECT_ROOT / "reports"
    summary_path = reports / "training_summary.json"
    audit_path = reports / "data_audit.json"

    for path, cmd in ((summary_path, "train run"), (audit_path, "data audit")):
        if not path.is_file():
            raise FileNotFoundError(f"{path} not found. Run `uv run mlservice {cmd}` first.")

    out_path = out_path or PROJECT_ROOT / "docs" / "MODEL_CARD.md"
    out_path.write_text(
        render(
            json.loads(summary_path.read_text(encoding="utf-8")),
            json.loads(audit_path.read_text(encoding="utf-8")),
        ),
        encoding="utf-8",
    )
    log.info("model_card_rendered", path=str(out_path))
    return out_path


__all__ = ["render", "render_to_file"]
