"""Render ``docs/MODEL_CARD.md`` from ``reports/training_summary.json``.

Generated, not written by hand, for the same reason the data audit is: a model
card transcribed manually goes stale the first time anyone retrains, and a stale
model card is worse than none — it states numbers the deployed model does not
produce.

Follows the Mitchell et al. (2019) structure, with out-of-scope use and
subgroup performance treated as mandatory rather than optional sections.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from mlservice.config import PROJECT_ROOT, get_settings, get_thresholds
from mlservice.data import schema
from mlservice.logging_ import get_logger
from mlservice.models.evaluate import TARGET_RECALL

log = get_logger(__name__)


def _pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def _normalise_markdown(text: str) -> str:
    """Blank lines where markdown needs them, without splitting tables apart."""
    out: list[str] = []
    for line in text.splitlines():
        previous = out[-1] if out else ""
        heading = line.startswith("#")
        table_start = line.startswith("|") and not previous.startswith("|")
        table_end = previous.startswith("|") and not line.startswith("|")
        if (heading or table_start or table_end) and previous.strip() and line.strip():
            out.append("")
        out.append(line)
        if heading:
            out.append("")

    collapsed: list[str] = []
    for line in out:
        if not line.strip() and collapsed and not collapsed[-1].strip():
            continue
        collapsed.append(line)
    return "\n".join(collapsed).strip() + "\n"


def render(summary: dict[str, Any], audit: dict[str, Any]) -> str:
    settings = get_settings()
    thresholds = get_thresholds().model_dump()

    champ = next(c for c in summary["candidates"] if c["name"] == summary["champion"])
    sub = champ["subgroups"]
    cal = champ["calibration"]
    heuristic = next(b for b in audit["baselines"] if b["name"].startswith("heuristic"))
    majority = next(b for b in audit["baselines"] if b["name"] == "majority_class")

    out: list[str] = []
    add = out.append

    add("# Model Card — Credit Default Risk\n")
    add(
        "> ## NOT A CREDIT DECISIONING SYSTEM\n>\n"
        "> This model is an **engineering demonstration of ML operations**. It "
        "has\n> never been validated for lending, is not compliant with any "
        "fair-lending\n> or adverse-action regime, and must never be used to "
        "decide anyone's\n> access to credit or the price of it. It is trained "
        "on a public research\n> dataset of loans issued 2007–2015 by a single "
        "lender.\n"
    )
    add(
        "> Generated by `uv run mlservice train run` from "
        "`reports/training_summary.json`. Do not edit by hand — regenerate it.\n"
    )
    add("---\n")

    # ------------------------------------------------------------------ details
    add("## Model details\n")
    add(
        f"| | |\n|:--|:--|\n"
        f"| Name | `{settings.model.name}` |\n"
        f"| Version | {summary.get('registered_version') or 'unregistered'} |\n"
        f"| Type | {summary['champion']} — regularised logistic regression |\n"
        f"| Calibration | {summary['calibration_method']}, fitted on validation |\n"
        f"| Decision threshold | {summary['champion_threshold']:.4f} |\n"
        f"| Feature schema hash | `{summary['feature_schema_hash']}` |\n"
        f"| Training rows | {summary['splits']['train']:,} |\n"
        f"| Licence | MIT (code); dataset per its own terms |\n"
    )

    # ------------------------------------------------------------- intended use
    add("## Intended use\n")
    add(
        "**Intended:** demonstrating a production ML lifecycle — serving, "
        "monitoring, drift detection, calibration-gated retraining and rollback. "
        "The model exists so that there is something real to operate.\n"
    )
    add("### Out-of-scope use\n")
    add(
        "Stated at equal prominence because it is the more important half:\n\n"
        "- **Any actual lending decision.** Not validated, not compliant, not "
        "lawful to use as an underwriting or pricing system.\n"
        "- **Adverse action.** US lenders must give specific reasons for denial. "
        "A calibrated logistic regression can support that; this model has had no "
        "such review, and its coefficients have not been examined for proxy "
        "discrimination.\n"
        "- **Individual risk communication.** At the operating threshold "
        f"{_pct(1 - champ['precision'])} of flagged loans are repaid in full. "
        "Telling a borrower they are likely to default on this basis would be "
        "wrong roughly three times in four.\n"
        "- **Any population outside the training distribution** — US unsecured "
        "personal loans, 2007–2015, one platform, 36- and 60-month terms.\n"
        "- **Transfer to current lending.** The book grew a thousandfold across "
        "the period and the credit policy changed repeatedly inside it.\n"
    )

    add("## Training data\n")
    add(
        f"Lending Club accepted loans — {audit['dataset']['rows']:,} loans issued "
        f"2007-06 to 2018-12 by one US platform. After cleaning: "
        f"{audit['leakage']['rows_out']:,} rows "
        f"({audit['leakage']['pct_removed']}% removed).\n"
    )
    add(
        "Exclusions and their reasons are in "
        "[DATA_AUDIT.md](DATA_AUDIT.md). The load-bearing ones:\n\n"
        "- **31 post-origination columns dropped** — a deterministic leak. "
        "Training on them reaches ROC-AUC 0.9983 against an honest ~0.70, and "
        "`recoveries > 0` labels a default 100% of the time.\n"
        "- **`loan_status` dropped** — it is the column the target is derived "
        "from, so it predicts the label perfectly. It survived the first pass "
        "because the data dictionary calls it a loan attribute, which it is, "
        "right up until you make it the label.\n"
        "- **Matured terms only** — a loan whose term has not elapsed has not "
        "had time to default, so its absence of default is not evidence of "
        "repayment. This moves the positive rate from 0.1998 to 0.1481.\n"
        "- **In-flight loans dropped** — `Late` and `In Grace Period` are not "
        "negatives. A loan 90 days late will probably charge off, but probably "
        "is not a label.\n"
        "- **42 sparse columns dropped** — fields Lending Club added partway "
        "through the period are null for every earlier loan, which under a "
        "chronological split proxies for the era rather than the borrower.\n"
    )
    add(
        f"**Split:** {summary['splits']['train']:,} train / "
        f"{summary['splits']['val']:,} validation / {summary['splits']['test']:,} test, "
        "chronological on `issue_d` — **a real date**, so the split is correct by "
        "construction and needs no argument that an ordering carries time "
        "signal. Cut on month boundaries, because loans issued in the same month "
        "share a credit policy.\n"
    )

    # ------------------------------------------------------------------ metrics
    add("## Performance\n")
    add(
        "PR-AUC is the headline. At a "
        f"{champ['prevalence'] * 100:.2f}% positive rate ROC-AUC is dominated by "
        "the large negative class and moves without changing what happens to the "
        "loans that actually default.\n"
    )
    pr, roc, br = champ["pr_auc"], champ["roc_auc"], champ["brier"]
    add(
        f"| Metric | Value | 95% CI |\n|:--|--:|:--|\n"
        f"| **PR-AUC** | **{pr['point']:.4f}** | [{pr['lower']:.4f}, {pr['upper']:.4f}] |\n"
        f"| ROC-AUC | {roc['point']:.4f} | [{roc['lower']:.4f}, {roc['upper']:.4f}] |\n"
        f"| Brier | {br['point']:.4f} | [{br['lower']:.4f}, {br['upper']:.4f}] |\n"
        f"| ECE (10 bins) | {cal['ece']:.4f} | — |\n"
        f"| MCE (worst bin) | {cal['mce']:.4f} | — |\n"
    )
    add("### Against the baselines it must beat\n")
    hl, hu = heuristic["pr_auc_ci"]
    overlaps = not (pr["upper"] < hl or hu < pr["lower"])
    add(
        f"| Model | PR-AUC | 95% CI |\n|:--|--:|:--|\n"
        f"| Prevalence floor | {champ['prevalence']:.4f} | — |\n"
        f"| `int_rate` heuristic — the lender's own priced risk | "
        f"{heuristic['pr_auc']:.4f} | [{hl:.4f}, {hu:.4f}] |\n"
        f"| **This model** | **{pr['point']:.4f}** | [{pr['lower']:.4f}, {pr['upper']:.4f}] |\n"
    )
    add(
        f"The intervals **{'overlap' if overlaps else 'do not overlap'}**, so the "
        f"model {'has not' if overlaps else 'has'} demonstrably beaten a "
        "one-feature heuristic available at admission with no model at all. That "
        "was the bar for justifying the serving, monitoring and retraining "
        "infrastructure.\n"
    )
    add(
        f"For contrast, the majority-class baseline scores "
        f"**{majority['accuracy']:.1%} accuracy with {majority['recall']:.0%} recall.** "
        "This is why accuracy is not reported as a headline metric.\n"
    )

    # --------------------------------------------------------------- operating
    add("## Operating point, stated honestly\n")
    add(
        f"The threshold ({summary['champion_threshold']:.4f}) was chosen **on "
        f"validation** to reach {_pct(TARGET_RECALL)} "
        "recall. On the held-out test split:\n"
    )
    add(
        f"| | |\n|:--|--:|\n"
        f"| Recall | {champ['recall']:.3f} |\n"
        f"| Precision | {champ['precision']:.3f} |\n"
        f"| Loans flagged | {_pct(champ['flagged_rate'])} |\n"
        f"| Lift over prevalence | {champ['lift_over_prevalence']}× |\n"
        f"| True positives | {champ['true_positives']:,} |\n"
        f"| False positives | {champ['false_positives']:,} |\n"
        f"| False negatives | {champ['false_negatives']:,} |\n"
    )
    add(
        f"**Read those numbers plainly.** To catch {champ['recall']:.0%} of "
        f"defaults the model flags {_pct(champ['flagged_rate'])} of all "
        f"loans, and {_pct(1 - champ['precision'])} of those flags are wrong. "
        f"It produces {champ['false_positives']:,} false alarms for "
        f"{champ['true_positives']:,} true ones. That is the real trade-off at "
        "this prevalence, and no threshold choice escapes it — it is a property "
        "of the problem, not a defect of the model.\n"
    )
    add(
        "Recall on test "
        f"({champ['recall']:.3f}) also fell short of the validation target "
        f"({champ['threshold_info']['achieved_recall']:.3f}). A threshold tuned on "
        "one time period does not transfer perfectly to the next — which is "
        "precisely the behaviour the monitoring in Phase 6 exists to detect.\n"
    )

    # ------------------------------------------------------------- calibration
    add("## Calibration\n")
    add(
        "Calibration is a **deployment gate** in this project, not a report "
        "([ADR 0002](DECISIONS/0002-calibration-as-deployment-gate.md)). A "
        "challenger that ranks better but calibrates worse is blocked.\n"
    )
    gate = thresholds["promotion"]["calibration"]
    add(
        f"| | Value | Gate | Status |\n|:--|--:|--:|:--|\n"
        f"| ECE (10 bins) | {cal['ece']:.4f} | ≤ {gate['max_ece']} | "
        f"{'PASS' if cal['ece'] <= gate['max_ece'] else 'FAIL'} |\n"
        f"| Brier | {br['point']:.4f} | — | — |\n"
        f"| MCE (worst bin) | {cal['mce']:.4f} | — | reported, not gated |\n"
    )
    # Read the ECE/MCE disagreement out of the run rather than hardcoding it.
    # A generated card that states last month's numbers is worse than no card.
    scored = [c for c in summary["candidates"] if c.get("calibration", {}).get("ece")]
    best_ece = min(scored, key=lambda c: c["calibration"]["ece"]) if scored else None
    worst_mce = max(scored, key=lambda c: c["calibration"]["mce"]) if scored else None

    add(
        "MCE is reported alongside ECE because they can disagree sharply, and a "
        "single number would hide it.\n"
    )
    if best_ece and worst_mce and best_ece["name"] == worst_mce["name"]:
        add(
            f"\nIn this run `{best_ece['name']}` held the **best** ECE "
            f"({best_ece['calibration']['ece']:.4f}) *and* the **worst** MCE "
            f"({worst_mce['calibration']['mce']:.4f}) — one probability bin was "
            "badly wrong while the count-weighted average looked healthy.\n"
        )
    elif best_ece and worst_mce:
        add(
            f"\nIn this run the best ECE was `{best_ece['name']}` "
            f"({best_ece['calibration']['ece']:.4f}) while the worst MCE was "
            f"`{worst_mce['name']}` ({worst_mce['calibration']['mce']:.4f}).\n"
        )
    add("![Reliability diagram](images/reliability_test.png)\n")

    # --------------------------------------------------------------- subgroups
    add("## Subgroup performance\n")
    add(
        "Reported for every subgroup above n="
        f"{sub['min_subgroup_n']}, **including where the results are "
        "unflattering.** Selective reporting would be worse than no fairness "
        "analysis, because it implies a check that was not really performed.\n"
    )
    add(
        "The same threshold is applied to every group. Per-group thresholds "
        "would improve these numbers and would mean setting a different "
        "approval bar by geography or income — disparate treatment, and the "
        "thing this analysis exists to detect rather than to implement.\n"
    )

    # Driven by the schema rather than hardcoded. The medical version listed
    # ("race", "gender", "age") inline, which silently rendered nothing at all
    # once the dimensions changed — a fairness section that disappears without
    # complaint is worse than one that is missing loudly.
    for dim in schema.SUBGROUP_DIMENSIONS:
        rows = [g for g in sub["groups"] if g["dimension"] == dim]
        if not rows:
            continue
        add(f"### `{dim}`\n")
        add("| Group | n | Positives | Recall | Precision | Gap vs overall | Analysed |\n")
        add("|:--|--:|--:|--:|--:|--:|:--:|\n")

        # addr_state has 51 levels; showing all of them buries the finding.
        # The largest ten plus every group with a material gap is the readable
        # compromise, and the count of what is omitted is stated.
        ordered = sorted(rows, key=lambda r: -r["n"])
        notable = [g for g in ordered if abs(g["recall_gap_vs_overall"]) >= 0.10]
        shown = list({id(g): g for g in ordered[:10] + notable}.values())

        for g in sorted(shown, key=lambda r: -r["n"]):
            mark = "yes" if g["sufficient"] else "**no — n too small**"
            add(
                f"| {g['group']} | {g['n']:,} | {g['n_positive']:,} | "
                f"{g['recall']:.3f} | {g['precision']:.3f} | "
                f"{g['recall_gap_vs_overall']:+.3f} | {mark} |\n"
            )
        if len(shown) < len(rows):
            add(
                f"\n*{len(rows) - len(shown)} further `{dim}` groups omitted from this "
                "table: each is outside the ten largest and none has a recall gap "
                "beyond ±0.10. All of them are in `reports/training_summary.json`.*\n"
            )

    worst = max(
        (g for g in sub["groups"] if g["sufficient"]),
        key=lambda g: -g["recall_gap_vs_overall"],
    )
    add("### The disparities, stated without softening\n")

    # Derived from the run, never hardcoded: which group is worst is an
    # empirical result that a retrain can change, and a card asserting last
    # month's disparity would be actively misleading.
    def spread(dimension: str) -> tuple[dict[str, Any], dict[str, Any]] | None:
        eligible = [g for g in sub["groups"] if g["dimension"] == dimension and g["sufficient"]]
        if len(eligible) < 2:
            return None
        return (
            min(eligible, key=lambda g: g["recall"]),
            max(eligible, key=lambda g: g["recall"]),
        )

    # Driven by schema.SUBGROUP_DIMENSIONS, not by a list written out here.
    #
    # This loop spelled out ("race", "gender", "age") — dimensions that US
    # credit data legally excludes and this dataset has never had. `spread()`
    # returned None for each, the loop body never ran, and the model card
    # silently lost this entire narrative section. Nothing failed, because a
    # `continue` on missing data is indistinguishable from there being nothing
    # to say.
    #
    # A dimension with no gloss still renders; the gloss adds interpretation,
    # and its absence must not remove the finding.
    glosses = {
        "addr_state": (
            "Geography is also a top-ten coefficient, so this spread falls on "
            "something the model structurally relies on — which is precisely "
            "the terrain fair-lending analysis governs."
        ),
        "emp_length": "Employment length is a socioeconomic proxy, and is treated as one.",
        "home_ownership": "Housing tenure correlates with wealth, not only with risk.",
        "income_band": "The band is derived from stated income, which is self-reported.",
    }
    for dimension in schema.SUBGROUP_DIMENSIONS:
        gloss = glosses.get(dimension, "")
        pair = spread(dimension)
        if not pair:
            continue
        low, high = pair
        add(
            f"**`{dimension}`.** Recall runs from **{low['recall']:.3f}** "
            f"({low['group']}, n={low['n']:,}) to **{high['recall']:.3f}** "
            f"({high['group']}, n={high['n']:,}) — a spread of "
            f"{(high['recall'] - low['recall']) * 100:.1f} percentage points across "
            f"subgroups large enough to analyse. {gloss}\n"
        )
    add(
        "**The mechanism is visible in the coefficients, and it is "
        "uncomfortable.** Two facts about what drives this model:\n\n"
        "1. **`grade` and `sub_grade` dominate.** `grade_A` carries the largest "
        "single weight (-0.78), with `sub_grade_A1` next (-0.57). Those columns "
        "are *Lending Club's own risk assessment*, so this model substantially "
        "inherits their underwriting judgment — including any bias in it. A "
        "model that reproduces an existing lender's decisions will reproduce "
        "that lender's disparities, and will look accurate while doing so.\n"
        "2. **Geography is a top-ten signal.** Four of the ten largest "
        "coefficients are `addr_state` dummies. The worst subgroup gap falling "
        "on a state is therefore not incidental — state is structurally one of "
        "the strongest things the model uses.\n\n"
        "Geographic risk pricing is exactly the terrain fair-lending law "
        "governs, because location correlates with protected characteristics "
        "that the data deliberately omits. This model has had **no** "
        "disparate-impact review, and its state coefficients have not been "
        "examined for proxy discrimination. That work would be mandatory before "
        "any real use, and none of it has been done here.\n"
    )
    add(
        f"**Worst analysable gap: {worst['recall_gap_vs_overall']:+.3f} "
        f"({worst['dimension']}={worst['group']}).** The Phase 7 promotion gate "
        "blocks any challenger that widens this by more than 20% relative — the "
        "gate is anchored to the incumbent because no absolute fairness constant "
        "would be defensible on this data, and inventing one implies a guarantee "
        "the evaluation cannot support.\n"
    )

    # ------------------------------------------------------------- limitations
    add("## Limitations\n")
    add(
        "- **Repeat borrowers cannot be excluded.** `member_id` is null for "
        "every row, so the same person may appear in both train and test. "
        "Deduplicating by borrower is the standard defence and it is simply "
        "unavailable here; held-out metrics are inflated to whatever extent "
        "repeat borrowing occurs.\n"
        "- **The model inherits the lender's judgment.** `grade` and "
        "`sub_grade` are Lending Club's own risk output and carry the largest "
        "coefficients. Beating their pricing by 0.019 PR-AUC is a real but "
        "narrow margin, and part of the model's apparent skill is theirs.\n"
        f"- **Positive rate varies modestly across the split** "
        f"({audit['split']['positive_rate']['train'] * 100:.2f}% train → "
        f"{audit['split']['positive_rate']['test'] * 100:.2f}% test), which is a "
        "genuine cohort shift rather than an artefact — the maturity rule "
        "removed the censoring that would otherwise dominate it.\n"
        "- **Modest discrimination by design.** ROC-AUC near 0.70 is close to "
        "the published ceiling for this task. This project treats a "
        "well-operated modest model as the goal.\n"
        "- **One platform, 2007–2015, US unsecured personal loans only.**\n"
        "- **Documented subgroup disparities** that are not mitigated in the "
        "model, only measured and gated against worsening.\n"
        "- **Prior-utilisation dependence** makes the model sensitive to "
        "record completeness, which is itself unevenly distributed.\n"
    )

    # ----------------------------------------------------------------- selection
    add("## How this model was selected\n")
    rationale = summary["selection_rationale"]
    add(f"**Rule:** {rationale['rule']}.\n")
    add("| Candidate | PR-AUC | 95% CI | ECE | Chosen |\n|:--|--:|:--|--:|:--:|\n")
    for c in summary["candidates"]:
        p = c["pr_auc"]
        e = c["calibration"].get("ece") if c.get("calibration") else None
        mark = "**yes**" if c["name"] == summary["champion"] else ""
        add(
            f"| {c['name']} | {p['point']:.4f} | [{p['lower']:.4f}, {p['upper']:.4f}] | "
            f"{e:.4f} | {mark} |\n"
            if e is not None
            else f"| {c['name']} | {p['point']:.4f} | [{p['lower']:.4f}, {p['upper']:.4f}] | — | {mark} |\n"
        )
    add(f"\n{rationale['note']}\n")
    add(
        "**XGBoost was not tried.** It was admitted only on audit evidence of "
        "non-linear structure worth the operational cost, and the audit produced "
        "the opposite: an unconstrained decision tree — able to represent "
        "arbitrary interactions — reached 0.519 test ROC-AUC. The shallow random "
        "forest here likewise failed to beat logistic regression. There is no "
        "unexploited non-linear signal to buy. See "
        "[ADR 0005](DECISIONS/0005-model-selection.md).\n"
    )

    add("## Data source\n")
    add(
        "> Lending Club accepted-loans book, 2007–2018.\n>\n"
        "> Lending Club withdrew the official download, so the bytes come from a\n"
        "> community mirror on the Hugging Face hub. **The SHA256 in\n"
        "> `data/checksums.txt` is the source of truth, not the URL** — a mirror\n"
        "> that changed under us would alter every number in this card silently,\n"
        "> so the checksum is verified on every download and a mismatch fails\n"
        "> loudly.\n"
    )
    return _normalise_markdown("".join(out))


def render_to_file(out_path: Path | None = None) -> Path:
    reports = PROJECT_ROOT / "reports"
    summary_path = reports / "training_summary.json"
    audit_path = reports / "data_audit.json"

    for path, cmd in ((summary_path, "train run"), (audit_path, "data audit")):
        if not path.is_file():
            raise FileNotFoundError(f"{path} not found. Run `uv run mlservice {cmd}` first.")

    out_path = out_path or PROJECT_ROOT / "docs" / "MODEL_CARD.md"
    out_path.write_text(
        render(
            json.loads(summary_path.read_text(encoding="utf-8")),
            json.loads(audit_path.read_text(encoding="utf-8")),
        ),
        encoding="utf-8",
    )
    log.info("model_card_rendered", path=str(out_path))
    return out_path


__all__ = ["render", "render_to_file"]
